### ISSUE TITLE
Instructions in Readme file are not accurate

### ISSUE THREAD

**Issue by oushima** [d0sse/macFox-theme#1]
Hello,

I followed all the steps listed in the readme file.

I now have  Chrome folder inside my profile's folder.
But when I restart Firefox the old theme is still applied.

It should actually be inside this folder: `9tcxagdd.default-release`, which is inside the `Profiles` folder. Not the `Profiles` folder itself. on macOS at least.

`/Users/oushima/Library/Application Support/Firefox/Profiles/9tcxagdd.default-release`,

Quote:
<img width="933" alt="image" src="https://github.com/d0sse/macFox-theme/assets/27223330/b6ccf0ed-e982-4956-b1ac-3d1696208fd0">

**Comment by d0sse** [comment]
Modified 🙏
